# Generated by Django 5.0.3 on 2024-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="no_of_books_written",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
